### ISSUE TITLE
file_put_contents not working. Permission denied

### ISSUE THREAD

**Issue by delmicio** [Desarrollo-CeSPI/docker-php-5.3-alpine#2]
Hi,

The console shows several messages with permission problems. Like this...

> PHP Warning:  file_put_contents(/var/www/html/fileNotExist.log) [<a href='function.file-put-contents'>function.file-put-contents</a>]: failed to open stream: Permission denied in ...

I've tried adding this in my Docker file, but the problem persist.
```
FROM cespi/php-5.3:apache

RUN set -x ; \
    addgroup -g 1000 -S www-data ; \
    adduser -u 1000 -D -S -G www-data www-data ; \
    set -x ; \
    addgroup -g 1000 -S nobody ; \
    adduser -u 1000 -D -S -G nobody nobody ; \
    set -x ; \
    addgroup -g 1000 -S apache ; \
    adduser -u 1000 -D -S -G apache apache ;
```

**Comment by chrodriguez** [comment]
Hola @delmicio, supongo por el dominio en tu email sos de argenitna, así que sigo este thread en castellano. Evidentemente estás subiendo archivos a un directorio donde apache no tiene permisos. i entrás al contenedor con docker exec, corré `ps -ef` y verificá el uid de Apache. Luego, verificá si la carpeta donde tratás de hacer el upload (al parecer por el ejemplo es /var/www/html) tiene permiso para que apache escriba
