### ISSUE TITLE
cespi/php-5.3:modules-apache not getting AllowOverride

### ISSUE THREAD

**Issue by greenled** [Desarrollo-CeSPI/docker-php-5.3-alpine#3]
Hi. I see `apache2-foreground` script for images `cespi/php-5.3:apache` and `cespi/php-5.3:modules-apache` is different:

```
docker run cespi/php-5.3:apache sh -c "cat /usr/local/bin/apache2-foreground" | grep 'envsubst' --
```

> envsubst '${PORT},${APACHE_RUN_USER},${APACHE_RUN_GROUP},${APACHE_DOCUMENT_ROOT},${DIRECTORY_OPTIONS},${ALLOW_OVERRIDE}' < /usr/local/etc/httpd.conf.tpl > /etc/apache2/httpd.conf

```
docker run cespi/php-5.3:modules-apache sh -c "cat /usr/local/bin/apache2-foreground" | grep 'envsubst' --
```

> envsubst '${APACHE_RUN_USER},${APACHE_RUN_GROUP},${APACHE_DOCUMENT_ROOT}' < /usr/local/etc/httpd.conf.tpl > /etc/apache2/httpd.conf

As a result, I can only have configurable AllowOverride OR extra php modules with each image, but not both.

Is this the desired behavior or a bug?

**Comment by chrodriguez** [comment]
My mistake, please create a PR. I could fix it by next week, not before. Thanks in advanve

**Comment by greenled** [comment]
Ok, I will try to fix it. Thank you for the work done in the project.

**Comment by chrodriguez** [comment]
Por nada!! Espero tu aporte

**Comment by greenled** [comment]
So... `cespi/php-5.3:apache` and `cespi/php-5.3:modules-apache` are ~4 months old, like other tags without **-latest**. There are newer tags `cespi/php-5.3:apache-latest` and `cespi/php-5.3:modules-apache-latest`. Silly of me :facepalm: Will try tomorow with those ones.

I just read the docs, and the **-latest** part is not mentioned. Maybe the PR should be for the docs?

**Comment by chrodriguez** [comment]
Of course. It will be wellcome
