### ISSUE TITLE
docker-php-ext-install Error

### ISSUE THREAD

**Issue by wei98k** [Desarrollo-CeSPI/docker-php-5.3-alpine#5]
docker-php-ext-install mysql 

print error info 
```
configure: error: Cannot find MySQL header files under yes.
Note that the MySQL client library is not bundled anymore!
```

**Comment by chrodriguez** [comment]
Hi @helloMJW , which image are you using? If you need mysql, we provide images with most used modules (like mysql) within:

* cespi/php-5.3:modules-cli-latest
* cespi/php-5.3:modules-apache-latest
* cespi/php-5.3:modules-fpm-latest

In case you only need mysql, please review those Dockerfile images. For example, the lines you need are:

```
RUN apk add -U --no-cache autoconf mariadb-dev && docker-php-ext-install mysql pdo_mysql
```
